server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false
  jackson:
    default-property-inclusion: non_empty
  redis:
      redis:
          # Redis服务器连接密码
          password:
          # Redis数据库索引（默认为0）
          database: 0
          # Redis服务器连接端口
          port: 6379
          pool:
            # 连接池中的最大空闲连接
            max-idle: 8
            # 连接池中的最小空闲连接
            min-idle: 0
            # 连接池最大连接数（使用负值表示没有限制）
            max-active: 8
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-wait: -1
          # Redis服务器地址
          host: 192.168.0.106
          # 连接超时时间（毫秒）
          timeout: 5000
mybatis:
  mapper-locations: classpath:mybatis/mapping/*.xml
  type-aliases-package: com.xxx.model

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
